### ISSUE TITLE
Misspelling: trail -> trial

### ISSUE THREAD

**Issue by pkscout** [ChloeCodesThings/FakeCallWorkshop#8]
in the Twillo creation section I think "Add a trail phone number " is suppose to be "Add a trial phone number."  Unless I'm suppose to have a phone number for just when I go hiking.  '-)

**Comment by pkscout** [comment]
P.S. There are a couple instances where trail should be trial, so maybe a global search and replace...

**Comment by ChloeCodesThings** [comment]
Fixed- thanks! 😁
